[tool.poetry]
name = "secureboxed-api"
version = "0.1.0"
description = ""
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
readme = "README.md"
packages = [{include = "secureboxed_api"}]

[tool.poetry.dependencies]
python = ">=3.9"
fastapi = "^0.112.2"
cryptography = "^43.0.0"
pytest = "^8.3.2"
python-multipart = "^0.0.9"


[tool.poetry.group.dev.dependencies]
pytest = "*"
pylint = "*"
autopep8 = "*"
pytest-cov = "*"
pytest-flask = "*"
httpx = "*"
complexipy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini-options]
python_paths = [".", "tests"]
